version: '3'
services:
  db:
    image: postgres:13
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    image: guapi22/globant_tech 
    container_name: globant_tech
    restart: always
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5000:5000"

volumes:
  pg_data:
